/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Case = IDL.Record({
  'id' : IDL.Nat,
  'created' : IDL.Int,
  'clientName' : IDL.Text,
  'caseNumber' : IDL.Text,
  'caseType' : IDL.Text,
  'nextHearingDate' : IDL.Text,
  'notes' : IDL.Text,
  'courtName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCase' : IDL.Func([Case], [IDL.Nat], []),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getCase' : IDL.Func([IDL.Nat], [Case], ['query']),
  'updateCase' : IDL.Func([IDL.Nat, Case], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Case = IDL.Record({
    'id' : IDL.Nat,
    'created' : IDL.Int,
    'clientName' : IDL.Text,
    'caseNumber' : IDL.Text,
    'caseType' : IDL.Text,
    'nextHearingDate' : IDL.Text,
    'notes' : IDL.Text,
    'courtName' : IDL.Text,
  });
  
  return IDL.Service({
    'addCase' : IDL.Func([Case], [IDL.Nat], []),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'getAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getCase' : IDL.Func([IDL.Nat], [Case], ['query']),
    'updateCase' : IDL.Func([IDL.Nat, Case], [], []),
  });
};

export const init = ({ IDL }) => { return []; };